force-app/main/default/objects/Product_Video__c/Product_Video__c.object-meta.xml
<CustomObject>
    <label>Product Video</label>
    <nameField>
        <displayFormat>PV-{0000}</displayFormat>
        <label>Product Video Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Video__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Videos</relationshipLabel>
    <relationshipName>Product_Videos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Video__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <defaultValue>500</defaultValue>
    <label>Sequence</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Video__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>MP4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Video__c/fields/Video_URI__c.field-meta.xml
<CustomField>
    <fullName>Video_URI__c</fullName>
    <description>Enter the URI for the MP4 video.</description>
    <inlineHelpText>For videos hosted by external URLs, you will need to create a CSP Trusted Site for the domain.</inlineHelpText>
    <label>Video URI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Video__c/fields/YouTube_Video_Id__c.field-meta.xml
<CustomField>
    <fullName>YouTube_Video_Id__c</fullName>
    <label>YouTube Video Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Video_I18N__c/Product_Video_I18N__c.object-meta.xml
<CustomObject>
    <label>Product Video I18N</label>
    <nameField>
        <displayFormat>PVI-{0000}</displayFormat>
        <label>Product Video I18N Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Video I18Ns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Video_I18N__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>B2B_Product_Video_Locales</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Video_I18N__c/fields/Product_Video__c.field-meta.xml
<CustomField>
    <fullName>Product_Video__c</fullName>
    <label>Product Video</label>
    <referenceTo>Product_Video__c</referenceTo>
    <relationshipLabel>Product Video I18Ns</relationshipLabel>
    <relationshipName>Product_Video_I18Ns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductVideoController.cls
/*
 * Copyright (c) 2021, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class ProductVideoController {
    
    @AuraEnabled(Cacheable=true)
    public static String getVideos(String recordId, String maxNumVideos, String locale){
        
        List<ProductVideo> pvList = new List<ProductVideo>();

        Date currentDate = Date.today();

        Integer limitValue = Integer.valueOf(maxNumVideos);

        String localePrefix = locale.substring(0,2);

        String likeValue = localePrefix + '%';

        List<Product_Video__c> pvObjList = new List<Product_Video__c>();

        pvObjList = [Select Id, Title__c, Description__c, Language__c, YouTube_Video_Id__c, Type__c, Video_URI__c, 
        (Select Language__c, Title__c, Description__c from Product_Video_I18Ns__r)
        from Product_Video__c 
        where Product__c = :recordId
        and Active__c = true
        and Start_Date__c <= :currentDate
        and End_Date__c >= :currentDate 
        with SECURITY_ENFORCED 
        order by Sequence__c 
        limit :limitValue 
        ];

        for(Product_Video__c pvObj : pvObjList) {

            ProductVideo pv = new ProductVideo();
            pv.id = pvObj.Id;
            pv.title = pvObj.Title__c;
            pv.description = pvObj.Description__c;
            pv.type = pvObj.Type__c;
            pv.youTubeVideoId = pvObj.YouTube_Video_Id__c;
            pv.videoUri = pvObj.Video_URI__c;

            if(locale == pvObj.Language__c) {
                // We are good to go
               // System.debug('matching language found with parent record');
            }
            else {
                // See if there is a translation for the user's specific locale

                Boolean translationFound = false;

                for(Product_Video_I18N__c pi18n : pvObj.Product_Video_I18Ns__r) {
                    if(locale == pi18n.Language__c) {

                        pv.title = pi18n.Title__c;
                        pv.description = pi18n.Description__c;
                        translationFound = true;
                        break;
                    }
                }

                if(translationFound == false) {
                    // See if there is a translation for the user's locale prefix

                    for(Product_Video_I18N__c pi18n : pvObj.Product_Video_I18Ns__r) {

                        if(localePrefix == pi18n.Language__c.substring(0,2)) {

                            pv.title = pi18n.Title__c;
                            pv.description = pi18n.Description__c;
                            translationFound = true;
                            break;
                        }
                    }
                }
            }

            pvList.add(pv);
        }
       
        return JSON.serialize(pvList);
    }

    public class ProductVideo {
        public String id {get; set;}
        public String title {get; set;}
        public String description {get; set;}
        public String type {get; set;}
        public String youTubeVideoId {get; set;}
        public String videoUri {get; set;}
    }

}